
title: Vítek Dvořák
email: vitekdvorak70@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  # some short description will be here...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vitekdvorak.cz" # the base hostname & protocol for your site, e.g. http://example.com
github_username: vitekdvorak

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
